name: WhythehellPlugin

author: DK
website:
main: WhythehellPlugin

commands:
    whythehell:
      description: Why the hell everyone!
      usage: /why

    killplayer:
      description: Kills thy Player!
      usage: /killplayer <playername>


version: 0.1